apiVersion: v1
kind: Secret
metadata:
  name: alethic-ism-api-secret
  namespace: alethic
stringData:
#  ROUTING_FILE: "/app/config/routing.yaml/routing.yaml"
#  LOG_LEVEL: DEBUG
#  DATABASE_URL: "postgresql://<user>:<password>@alethic-db-service:5432/<db_name>"
  .firebase-credentials.json: |
    {
      "type": "service_account",
      "project_id": "ism",
      "private_key_id": "",
      "private_key": "",
      "client_email": "",
      "client_id": "",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://oauth2.googleapis.com/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "",
      "universe_domain": "googleapis.com"
    }
  .routing.yaml: |
    messageConfig:
        root_route:
          topic: ism_general
          manage_topic: ism_general_manage
          subscription: ism_general_subscription
          service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650

        topic_routes:
          - selector: state/router
            topic: ism_state_router
            subscription: ism_state_router_subscription
            service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650

